## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

### 載入所需元件

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [39]:
# 讀取鳶尾花資料集
iris = datasets.load_iris()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.7, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 建立一個邏輯回歸模型
logreg = linear_model.LogisticRegression()

# 將訓練資料丟進去模型訓練
logreg.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = logreg.predict(x_test)

### y_pred

In [40]:
print(y_pred)

[2 0 2 2 2 2 2 0 0 2 0 0 0 2 2 0 1 0 0 2 0 2 2 0 0 0 0 0 0 2 2 0 2 0 1 2 2
 1 1 0 2 0 1 0 2 0 0 2 2 2 0 1 2 2 1 2 0 1 2 2 0 2 0 1 2 2 2 2 0 2 2 0 1 2
 0 2 1 2 2 0 2 2 2 0 2 1 2 1 2 1 2 2 2 1 2 1 1 0 2 0 1 0 2 1 2]


In [41]:
# 可以看回歸模型的參數值
print('Coefficients: ', logreg.coef_)
print("------------------------------")
print(logreg.coef_)
#print(regr.coef_)

Coefficients:  [[ 0.25380927  1.13966671 -1.6802252  -0.76420402]
 [ 0.34195859 -1.21552908  0.36985872 -0.89055482]
 [-1.01838004 -0.86624077  1.49445079  1.58557859]]
------------------------------
[[ 0.25380927  1.13966671 -1.6802252  -0.76420402]
 [ 0.34195859 -1.21552908  0.36985872 -0.89055482]
 [-1.01838004 -0.86624077  1.49445079  1.58557859]]


In [42]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.17


In [43]:
# 讀取鳶尾花資料集
iris = datasets.load_iris()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=4)

# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [44]:
y_pred

array([1.20658922, 0.88577015, 1.24771987, 1.28885053, 1.26417214,
       1.11610179, 1.16545857, 0.8446395 , 0.88577015, 1.16545857,
       0.87754402, 0.87754402, 0.86109176, 1.13255405, 1.15723244,
       0.86931789, 1.03384049, 0.85286563, 0.90222241, 1.14900631,
       0.8446395 , 1.21481535, 1.11610179, 0.87754402, 0.87754402,
       0.86931789, 0.85286563, 0.85286563, 0.88577015, 1.16545857,
       1.11610179, 0.86109176, 1.22304148, 0.86109176, 1.01738823,
       1.21481535, 1.23949374, 1.07497114, 1.13255405, 0.87754402,
       1.24771987, 0.86931789, 1.10787566, 0.86931789, 1.20658922])

In [45]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([ 0.       , -0.       ,  0.0822613,  0.       ])

In [46]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.55


### Ridge

In [48]:
# 讀取糖尿病資料集
iris = datasets.load_iris()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha= 0.01)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = logreg.predict(x_test)
## y_pred(alpha=1.0), [2 0 2 2 2 2 2 0 0 2 0 0 0 2 2 0 1 0 0 2 0 2 2 0 0 0 0 0 0 2]
## y_pred(alpha=1.0), [2 0 2 2 2 2 2 0 0 2 0 0 0 2 2 0 1 0 0 2 0 2 2 0 0 0 0 0 0 2]
print(y_pred)

[2 0 2 2 2 2 2 0 0 2 0 0 0 2 2 0 1 0 0 2 0 2 2 0 0 0 0 0 0 2]


In [49]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
print(ridge.coef_)

[-0.13288173 -0.04438035  0.23843819  0.60132308]


In [50]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.13


In [35]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_svmlight_format',
 'base',
 'california_housing',
 'clear_data_home',
 'covtype',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_mldata',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'kddcup99',
 'lfw',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_mlcomp',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_classification',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2'